INSERT INTO chimiotherapie VALUES (1001,'Epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Paclitaxel hebdomadaire-Carboplatine',58),
	(1001,'Epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1001,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1001,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Pemetrexed',36),
	(1001,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Paclitaxel hebdomadaire-Carboplatine',58),
	(1001,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1003,'N/A','INF30','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Osimertinib',56),
	(1003,'Epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1003,'Epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1003,'Epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1003,'Epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1003,'Epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1003,'Epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1003,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Gemcitabine',34),
	(1003,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Docetaxel',33),
	(1003,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 50-Vinorelbine 25',29),
	(1003,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 100-Vinorelbine 30',26),
	(1003,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 75-Vinorelbine 25',32),
	(1003,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1003,'Non epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1003,'Non epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1003,'Non epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1003,'Non epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1003,'Non epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1003,'Non epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1003,'Non epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1003,'Non epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1003,'Non epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1003,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Pemetrexed',36),
	(1003,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 50-Vinorelbine 25',29),
	(1003,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 100-Vinorelbine 30',26),
	(1003,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 75-Vinorelbine 25',32),
	(1003,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1003,'Epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Paclitaxel hebdomadaire-Carboplatine',58),
	(1003,'Epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1003,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1003,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Pemetrexed',36),
	(1003,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Paclitaxel hebdomadaire-Carboplatine',58),
	(1003,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1003,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 50-Vinorelbine 25',19),
	(1004,'N/A','INF30','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Osimertinib',56),
	(1004,'Epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1004,'Epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1004,'Epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1004,'Epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1004,'Epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1004,'Epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1004,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Gemcitabine',34),
	(1004,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Docetaxel',33),
	(1004,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 50-Vinorelbine 25',29),
	(1004,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 100-Vinorelbine 30',26),
	(1004,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 75-Vinorelbine 25',32),
	(1004,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1004,'Non epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1004,'Non epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1004,'Non epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1004,'Non epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1004,'Non epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1004,'Non epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1004,'Non epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1004,'Non epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1004,'Non epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1004,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Pemetrexed',36),
	(1004,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 50-Vinorelbine 25',29),
	(1004,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 100-Vinorelbine 30',26),
	(1004,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 75-Vinorelbine 25',32),
	(1004,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1005,'Epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Paclitaxel hebdomadaire-Carboplatine',58),
	(1005,'Epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1005,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1005,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Pemetrexed',36),
	(1005,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Paclitaxel hebdomadaire-Carboplatine',58),
	(1005,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Pembrolizumab',59),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Pembrolizumab',59),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Pembrolizumab',59),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab 840',3),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab 1200',4),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab 1680',5),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab 840',3),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab 1200',4),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab 1680',5),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab 840',3),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab 1200',4),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab 1680',5),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Cemiplimab-rwlc',24),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Cemiplimab-rwlc',24),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Cemiplimab-rwlc',24),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Pembrolizumab',59),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Pembrolizumab',59),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Pembrolizumab',59),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Docetaxel',13),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Etoposide',14),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','nabPaclitaxel',51),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Docetaxel',41),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Gemcitabine',46),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Paclitaxel',57),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Dabrafenib-Trametinib',39),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Dabrafenib-Trametinib',39),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Dabrafenib-Trametinib',39),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Dabrafenib-Trametinib',39),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Docetaxel',13),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Docetaxel',13),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Docetaxel',33),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Docetaxel',33),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Etoposide',27),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Etoposide',27),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Gemcitabine',34),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Gemcitabine',34),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Paclitaxel',35),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Paclitaxel',35),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Dabrafenib-Trametinib',39),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Docetaxel',13),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Etoposide',14),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','nabPaclitaxel',51),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Docetaxel',41),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Gemcitabine',46),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Paclitaxel',57),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Pembrolizumab',59),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Pembrolizumab',59),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Pembrolizumab',59),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab 840',3),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab 1200',4),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab 1680',5),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab 840',3),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab 1200',4),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab 1680',5),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab 840',3),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab 1200',4),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab 1680',5),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Cemiplimab-rwlc',24),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Cemiplimab-rwlc',24),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Cemiplimab-rwlc',24),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Pembrolizumab',59),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Pembrolizumab',59),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Pembrolizumab',59),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7);
INSERT INTO chimiotherapie VALUES (1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Pemetrexed',22),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Docetaxel',13),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Etoposide',14),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','nabPaclitaxel',51),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Docetaxel',41),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Gemcitabine',46),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Paclitaxel',57),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Pemetrexed',60),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Dabrafenib-Trametinib',39),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Dabrafenib-Trametinib',39),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Nivolumab-Ipilimumab-Pemetrexed',55),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Nivolumab-Ipilimumab-Pemetrexed',55),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Dabrafenib-Trametinib',39),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Dabrafenib-Trametinib',39),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Bevacizumab-Carboplatine-Paclitaxel',9),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Bevacizumab-Carboplatine-Paclitaxel',9),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Bevacizumab-Cisplatine-Pemetrexed',11),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Bevacizumab-Cisplatine-Pemetrexed',11),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Bevacizumab-Carboplatine-Pemetrexed',10),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Bevacizumab-Carboplatine-Pemetrexed',10),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Docetaxel',13),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Docetaxel',13),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Etoposide',14),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Etoposide',14),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Pemetrexed',22),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Pemetrexed',22),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Docetaxel',33),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Docetaxel',33),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Etoposide',27),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Etoposide',27),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Gemcitabine',34),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Gemcitabine',34),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Paclitaxel',35),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Paclitaxel',35),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Pemetrexed',36),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Pemetrexed',36),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Dabrafenib-Trametinib',39),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Pemetrexed',22),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Docetaxel',13),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Etoposide',14),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','nabPaclitaxel',51),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Docetaxel',41),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Gemcitabine',46),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Paclitaxel',57),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Pemetrexed',60),
	(1006,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','3','N/A','Meilleurs soins de soutien',50),
	(1006,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','4','N/A','Meilleurs soins de soutien',50),
	(1006,'N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','Alectinib',2),
	(1006,'N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','Brigatinib',12),
	(1006,'N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','Lorlatinib',49),
	(1006,'N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','Ceritinib',25),
	(1006,'N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','Crizotinib',38),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Osimertinib',56),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Gefitinib',44),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Erlotinib',43),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','bevacizumab',8),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','ramucirumab',61),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Afatinib',1),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Dacomitinib',40),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Gefitinib-Carboplatine-Pemetrexed',45),
	(1006,'N/A','N/A','N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','Entrectinib',42),
	(1006,'N/A','N/A','N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','Crizotinib',38),
	(1006,'N/A','N/A','N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','Ceritinib',25),
	(1006,'N/A','N/A','N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','Lorlatinib',49),
	(1006,'N/A','N/A','N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','Repotrectinib',62),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Pemetrexed',35),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Pemetrexed',35),
	(1007,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 75 + Etoposide',31),
	(1007,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 60 + Etoposide',30),
	(1007,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 25 + Etoposide',28),
	(1007,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Etoposide',14),
	(1007,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Negatif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Negatif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Positif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Positif','N/A','N/A','Non fumeur','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Positif','Positif','Negatif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Positif','Positif','Negatif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Positif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Positif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Negatif','Positif','N/A','N/A','Non fumeur','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Negatif','Positif','N/A','N/A','Non fumeur','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Positif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Positif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Negatif','Positif','N/A','N/A','Non fumeur','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Negatif','Positif','N/A','N/A','Non fumeur','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Positif','Positif','N/A','N/A','Non fumeur','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Positif','Positif','N/A','N/A','Non fumeur','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','Non fumeur','Pembrolizumab',59),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','Non fumeur','Atezolizumab 840',3),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','Non fumeur','Atezolizumab 1200',4),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','Non fumeur','Atezolizumab 1680',5),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','Non fumeur','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','Non fumeur','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','Non fumeur','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','Non fumeur','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','Non fumeur','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','Non fumeur','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','Non fumeur','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','Non fumeur','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','Non fumeur','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','Non fumeur','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','Non fumeur','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','Non fumeur','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','Non fumeur','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','Non fumeur','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','Non fumeur','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','3','Non fumeur','Meilleurs soins de soutien',50),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','4','Non fumeur','Meilleurs soins de soutien',50),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Negatif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Negatif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Positif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Positif','N/A','N/A','INF15PA','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Positif','Positif','Negatif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Positif','Positif','Negatif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Positif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Positif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Negatif','Positif','N/A','N/A','INF15PA','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Negatif','Positif','N/A','N/A','INF15PA','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Positif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Positif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Negatif','Positif','N/A','N/A','INF15PA','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Negatif','Positif','N/A','N/A','INF15PA','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Positif','Positif','N/A','N/A','INF15PA','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Positif','Positif','N/A','N/A','INF15PA','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','INF15PA','Pembrolizumab',59),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','INF15PA','Atezolizumab 840',3),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','INF15PA','Atezolizumab 1200',4),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','INF15PA','Atezolizumab 1680',5),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','INF15PA','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','INF15PA','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','INF15PA','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','INF15PA','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','INF15PA','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','INF15PA','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','INF15PA','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','INF15PA','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','INF15PA','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','INF15PA','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','INF15PA','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','INF15PA','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','INF15PA','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','INF15PA','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','INF15PA','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','3','INF15PA','Meilleurs soins de soutien',50),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','4','INF15PA','Meilleurs soins de soutien',50),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','Positif > 50%','N/A','SUP15PA','Pembrolizumab',59),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','Positif > 50%','N/A','SUP15PA','Atezolizumab 840',3),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','Positif > 50%','N/A','SUP15PA','Atezolizumab 1200',4),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','Positif > 50%','N/A','SUP15PA','Atezolizumab 1680',5),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','0','SUP15PA','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','1','SUP15PA','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','2','SUP15PA','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','0','SUP15PA','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','1','SUP15PA','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','2','SUP15PA','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','0','SUP15PA','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','1','SUP15PA','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','2','SUP15PA','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','0','SUP15PA','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','1','SUP15PA','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','2','SUP15PA','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','0','SUP15PA','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','1','SUP15PA','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','2','SUP15PA','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','3','SUP15PA','Meilleurs soins de soutien',50),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','4','SUP15PA','Meilleurs soins de soutien',50);

INSERT INTO protocole VALUES (1,'Afatinib','-','Afatinib','40','mg/j','tous les jours','orale'),
	(2,'Alectinib','-','Alectinib','300','mg x2/j','tous les jours','orale'),
	(3,'Atezolizumab 840','14','Atezolizumab','840','mg','1','IV'),
	(4,'Atezolizumab 1200','21','Atezolizumab','1200','mg','1','IV'),
	(5,'Atezolizumab 1680','28','Atezolizumab','1680','mg','1','IV'),
	(6,'Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel','21','Atezolizumab','1200','mg','1','IV'),
	(6,'Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel','21','Bevacizumab','15','mg/kg','1','IV'),
	(6,'Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel','21','Carboplatine','6','AUC','1','IV'),
	(6,'Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel','21','Paclitaxel','200','mg/m2','1','IV'),
	(7,'Atezolizumab-Carboplatine-nabPaclitaxel','21','Atezolizumab','1200','mg','1','IV'),
	(7,'Atezolizumab-Carboplatine-nabPaclitaxel','21','Carboplatine','6','AUC','1','IV'),
	(7,'Atezolizumab-Carboplatine-nabPaclitaxel','7','nabPaclitaxel','100','mg/m2','1','IV'),
	(8,'Bevacizumab','21','Bevacizumab','15','mg/kg','1','IV'),
	(9,'Bevacizumab-Carboplatine-Paclitaxel','21','Bevacizumab','15','mg/kg','1','IV'),
	(9,'Bevacizumab-Carboplatine-Paclitaxel','21','Carboplatine','6','AUC','1','IV'),
	(9,'Bevacizumab-Carboplatine-Paclitaxel','21','Paclitaxel','200','mg/m2','1','IV'),
	(10,'Bevacizumab-Carboplatine-Pemetrexed','21','Bevacizumab','15','mg/kg','1','IV'),
	(10,'Bevacizumab-Carboplatine-Pemetrexed','21','Carboplatine','6','AUC','1','IV'),
	(10,'Bevacizumab-Carboplatine-Pemetrexed','21','Pemetrexed','500','mg/m2','1','IV'),
	(11,'Bevacizumab-Cisplatine-Pemetrexed','21','Bevacizumab','15','mg/kg','1','IV'),
	(11,'Bevacizumab-Cisplatine-Pemetrexed','21','Cisplatine','75','mg/m2','1','IV'),
	(11,'Bevacizumab-Cisplatine-Pemetrexed','21','Pemetrexed','500','mg/m2','1','IV'),
	(12,'Brigatinib','-','Brigatinib','180','mg/j','tous les jours','orale'),
	(13,'Carboplatine-Docetaxel','21','Carboplatine','6','AUC','1','IV'),
	(13,'Carboplatine-Docetaxel','21','Docetaxel','75','mg/m2','1','IV'),
	(14,'Carboplatine-Etoposide','-','Carboplatine','5 à 6','AUC','1','IV'),
	(14,'Carboplatine-Etoposide','-','Etoposide','100','mg/m2','1','IV'),
	(14,'Carboplatine-Etoposide','-','Etoposide','100','mg/m2','2','IV'),
	(14,'Carboplatine-Etoposide','-','Etoposide','100','mg/m2','3','IV'),
	(15,'Carboplatine-Gemcitabine','21','Carboplatine','5','AUC','1','IV'),
	(15,'Carboplatine-Gemcitabine','21','Gemcitabine','1000','mg/m2','1','IV'),
	(15,'Carboplatine-Gemcitabine','21','Gemcitabine','1000','mg/m2','8','IV'),
	(16,'Carboplatine-nabPaclitaxel','21','Carboplatine','5','AUC','1','IV'),
	(16,'Carboplatine-nabPaclitaxel','21','nabPaclitaxel','100','mg/m2','1','IV'),
	(17,'Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab','21','Carboplatine','5','AUC','1','IV'),
	(17,'Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab','21','nabPaclitaxel','100','mg/m2','1','IV'),
	(17,'Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab','56','Nivolumab','6','mg/kg','1','IV'),
	(17,'Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab','56','Nivolumab','480','mg','29','IV'),
	(17,'Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab','56','Ipilimumab','1','mg/kg','1','IV'),
	(18,'Carboplatine-nabPaclitaxel-Pembrolizumab','21','Carboplatine','5','AUC','1','IV'),
	(18,'Carboplatine-nabPaclitaxel-Pembrolizumab','21','nabPaclitaxel','100','mg/m2','1','IV'),
	(18,'Carboplatine-nabPaclitaxel-Pembrolizumab','21','Pembrolizumab','200','mg','1','IV'),
	(19,'Carboplatine-Paclitaxel','21','Carboplatine','6','AUC','1','IV'),
	(19,'Carboplatine-Paclitaxel','21','Paclitaxel','200','mg/m2','1','IV'),
	(20,'Carboplatine-Paclitaxel-Nivolumab-Ipilimumab','21','Carboplatine','6','AUC','1','IV'),
	(20,'Carboplatine-Paclitaxel-Nivolumab-Ipilimumab','21','Paclitaxel','200','mg/m2','1','IV'),
	(20,'Carboplatine-Paclitaxel-Nivolumab-Ipilimumab','56','Nivolumab','6','mg/kg','1','IV'),
	(20,'Carboplatine-Paclitaxel-Nivolumab-Ipilimumab','56','Nivolumab','480','mg','29','IV'),
	(20,'Carboplatine-Paclitaxel-Nivolumab-Ipilimumab','56','Ipilimumab','1','mg/kg','1','IV'),
	(21,'Carboplatine-Paclitaxel-Pembrolizumab','21','Carboplatine','6','AUC','1','IV'),
	(21,'Carboplatine-Paclitaxel-Pembrolizumab','21','Paclitaxel','200','mg/m2','1','IV'),
	(21,'Carboplatine-Paclitaxel-Pembrolizumab','21','Pembrolizumab','200','mg','1','IV'),
	(22,'Carboplatine-Pemetrexed','21','Carboplatine','5','AUC','1','IV'),
	(22,'Carboplatine-Pemetrexed','21','Pemetrexed','500','mg/m2','1','IV'),
	(23,'Carboplatine-Pemetrexed-Pembrolizumab','21','Carboplatine','6','AUC','1','IV'),
	(23,'Carboplatine-Pemetrexed-Pembrolizumab','21','Pemetrexed','500','mg/m2','1','IV'),
	(23,'Carboplatine-Pemetrexed-Pembrolizumab','21','Pembrolizumab','200','mg','1','IV'),
	(24,'Cemiplimab-rwlc','21','Cemiplimab-rwlc','350','mg','1','IV'),
	(25,'Ceritinib','-','Ceritinib','250','mg/j','tous les jours','orale'),
	(26,'Cisplatine 100-Vinorelbine 30','28','Cisplatine','100','mg/m2','1','IV'),
	(26,'Cisplatine 100-Vinorelbine 30','28','Vinorelbine','30','mg/m2','1','IV'),
	(26,'Cisplatine 100-Vinorelbine 30','28','Vinorelbine','30','mg/m2','8','IV'),
	(26,'Cisplatine 100-Vinorelbine 30','28','Vinorelbine','30','mg/m2','15','IV'),
	(26,'Cisplatine 100-Vinorelbine 30','28','Vinorelbine','30','mg/m2','22','IV'),
	(27,'Cisplatine-Etoposide','28','Cisplatine','50','mg/m2','1','IV'),
	(27,'Cisplatine-Etoposide','28','Cisplatine','50','mg/m2','8','IV'),
	(27,'Cisplatine-Etoposide','28','Etoposide','50','mg/m2','1','IV'),
	(27,'Cisplatine-Etoposide','28','Etoposide','50','mg/m2','5','IV'),
	(28,'Cisplatine 25 + Etoposide','-','Cisplatine','25','mg/m2','1','IV'),
	(28,'Cisplatine 25 + Etoposide','-','Cisplatine','25','mg/m2','2','IV'),
	(28,'Cisplatine 25 + Etoposide','-','Cisplatine','25','mg/m2','3','IV'),
	(28,'Cisplatine 25 + Etoposide','-','Etoposide','100','mg/m2','1','IV'),
	(28,'Cisplatine 25 + Etoposide','-','Etoposide','100','mg/m2','2','IV'),
	(28,'Cisplatine 25 + Etoposide','-','Etoposide','100','mg/m2','3','IV'),
	(29,'Cisplatine 50-Vinorelbine 25','28','Cisplatine','50','mg/m2','1','IV'),
	(29,'Cisplatine 50-Vinorelbine 25','28','Cisplatine','50','mg/m2','8','IV'),
	(29,'Cisplatine 50-Vinorelbine 25','28','Vinorelbine','25','mg/m2','1','IV'),
	(29,'Cisplatine 50-Vinorelbine 25','28','Vinorelbine','25','mg/m2','8','IV'),
	(29,'Cisplatine 50-Vinorelbine 25','28','Vinorelbine','25','mg/m2','15','IV'),
	(29,'Cisplatine 50-Vinorelbine 25','28','Vinorelbine','25','mg/m2','22','IV'),
	(30,'Cisplatine 60 + Etoposide','-','Cisplatine','60','mg/m2','1','IV'),
	(30,'Cisplatine 60 + Etoposide','-','Etoposide','120','mg/m2','1','IV'),
	(30,'Cisplatine 60 + Etoposide','-','Etoposide','120','mg/m2','2','IV'),
	(30,'Cisplatine 60 + Etoposide','-','Etoposide','120','mg/m2','3','IV'),
	(31,'Cisplatine 75 + Etoposide','-','Cisplatine','75','mg/m2','1','IV'),
	(31,'Cisplatine 75 + Etoposide','-','Etoposide','100','mg/m2','1','IV'),
	(31,'Cisplatine 75 + Etoposide','-','Etoposide','100','mg/m2','2','IV'),
	(31,'Cisplatine 75 + Etoposide','-','Etoposide','100','mg/m2','3','IV'),
	(32,'Cisplatine 75-Vinorelbine 25','21','Cisplatine','75-80','mg/m2','1','IV'),
	(32,'Cisplatine 75-Vinorelbine 25','21','Vinorelbine','25-30','mg/m2','1','IV'),
	(32,'Cisplatine 75-Vinorelbine 25','21','Vinorelbine','25-30','mg/m2','8','IV'),
	(33,'Cisplatine-Docetaxel','21','Cisplatine','75','mg/m2','1','IV'),
	(33,'Cisplatine-Docetaxel','21','Docetaxel','75','mg/m2','1','IV'),
	(34,'Cisplatine-Gemcitabine','21','Cisplatine','75','mg/m2','1','IV'),
	(34,'Cisplatine-Gemcitabine','21','Gemcitabine','1250','mg/m2','1','IV'),
	(34,'Cisplatine-Gemcitabine','21','Gemcitabine','1250','mg/m2','8','IV'),
	(35,'Cisplatine-Paclitaxel','21','Cisplatine','75','mg/m2','1','IV'),
	(35,'Cisplatine-Paclitaxel','21','Paclitaxel','200','mg/m2','1','IV'),
	(36,'Cisplatine-Pemetrexed','21','Cisplatine','75','mg/m2','1','IV'),
	(36,'Cisplatine-Pemetrexed','21','Pemetrexed','500','mg/m2','1','IV'),
	(37,'Cisplatine-Pemetrexed -Pembrolizumab','21','Cisplatine','75','mg/m2','1','IV'),
	(37,'Cisplatine-Pemetrexed -Pembrolizumab','21','Pemetrexed','500','mg/m2','1','IV'),
	(37,'Cisplatine-Pemetrexed -Pembrolizumab','21','Pembrolizumab','200','mg','1','IV'),
	(38,'Crizotinib','-','Crizotinib','250','mg/j','tous les jours','Orale'),
	(39,'Dabrafenib-Trametinib','-','Dabrafenib','150','mg x2/j','tous les jours','Orale'),
	(39,'Dabrafenib-Trametinib','-','Trametinib','2','mg/j','tous les jours','Orale'),
	(40,'Dacomitinib','-','Dacomitinib','45','mg/j','tous les jours','Orale'),
	(41,'Docetaxel','21','Docetaxel','75','mg/m2','1','IV'),
	(42,'Entrectinib','-','Entrectinib','600','mg/j','tous les jours','Orale'),
	(43,'Erlotinib','-','Erlotinib','150','mg/j','tous les jours','Orale'),
	(44,'Gefitinib','-','Gefitinib','50','mg/j','tous les jours','Orale'),
	(45,'Gefitinib-Carboplatine-Pemetrexed','-','Gefitinib','50','mg/j','tous les jours','Orale'),
	(45,'Gefitinib-Carboplatine-Pemetrexed','21','Carboplatine','6','AUC','1','IV'),
	(45,'Gefitinib-Carboplatine-Pemetrexed','21','Pemetrexed','500','mg/m2','1','IV'),
	(46,'Gemcitabine','21','Gemcitabine','900','mg/m2','1','IV'),
	(46,'Gemcitabine','21','Gemcitabine','900','mg/m2','8','IV'),
	(47,'Gemcitabine-Docetaxel','21','Gemcitabine','900','mg/m2','1','IV'),
	(47,'Gemcitabine-Docetaxel','21','Gemcitabine','900','mg/m2','8','IV'),
	(47,'Gemcitabine-Docetaxel','21','Docetaxel','75','mg/m2','1','IV'),
	(48,'Gemcitabine-Vinorelbine','21','Gemcitabine','1000','mg/m2','1','IV'),
	(48,'Gemcitabine-Vinorelbine','21','Gemcitabine','1000','mg/m2','8','IV'),
	(48,'Gemcitabine-Vinorelbine','21','Vinorelbine','60','mg/m2','1','IV'),
	(49,'Lorlatinib','-','Lorlatinib','100','mg/j','tous les jours','Orale'),
	(51,'nabPaclitaxel','14','nabPaclitaxel','100','mg/m2','1','IV'),
	(52,'Nivolumab-Ipilimumab','56','Nivolumab','6','mg/kg','1','IV'),
	(52,'Nivolumab-Ipilimumab','56','Nivolumab','480','mg','29','IV'),
	(52,'Nivolumab-Ipilimumab','56','Ipilimumab','1','mg/kg','1','IV'),
	(53,'Nivolumab-Ipilimumab-Carboplatine-Pemetrexed','56','Nivolumab','6','mg/kg','1','IV'),
	(53,'Nivolumab-Ipilimumab-Carboplatine-Pemetrexed','56','Nivolumab','480','mg','29','IV'),
	(53,'Nivolumab-Ipilimumab-Carboplatine-Pemetrexed','56','Ipilimumab','1','mg/kg','1','IV'),
	(53,'Nivolumab-Ipilimumab-Carboplatine-Pemetrexed','21','Carboplatine','6','AUC','1','IV'),
	(53,'Nivolumab-Ipilimumab-Carboplatine-Pemetrexed','21','Pemetrexed','500','mg/m2','1','IV'),
	(54,'Nivolumab-Ipilimumab-Cisplatine-Pemetrexed','56','Nivolumab','6','mg/kg','1','IV'),
	(54,'Nivolumab-Ipilimumab-Cisplatine-Pemetrexed','56','Nivolumab','480','mg','29','IV'),
	(54,'Nivolumab-Ipilimumab-Cisplatine-Pemetrexed','56','Ipilimumab','1','mg/kg','1','IV'),
	(54,'Nivolumab-Ipilimumab-Cisplatine-Pemetrexed','21','Cisplatine','75','mg/m2','1','IV'),
	(54,'Nivolumab-Ipilimumab-Cisplatine-Pemetrexed','21','Pemetrexed','500','mg/m2','1','IV'),
	(55,'Nivolumab-Ipilimumab-Pemetrexed','56','Nivolumab','6','mg/kg','1','IV'),
	(55,'Nivolumab-Ipilimumab-Pemetrexed','56','Nivolumab','480','mg','29','IV'),
	(55,'Nivolumab-Ipilimumab-Pemetrexed','56','Ipilimumab','1','mg/kg','1','IV'),
	(55,'Nivolumab-Ipilimumab-Pemetrexed','21','Pemetrexed','500','mg/m2','1','IV'),
	(56,'Osimertinib','-','Osimertinib','80','mg par jour','tous les jours','IV'),
	(57,'Paclitaxel','7','Paclitaxel','60','mg/m2','1','IV'),
	(58,'Paclitaxel hebdomadaire-Carboplatine','7','Paclitaxel','45-50','mg/m2','1','IV'),
	(58,'Paclitaxel hebdomadaire-Carboplatine','7','Carboplatine','2','AUC','1','IV'),
	(59,'Pembrolizumab','21','Pembrolizumab','200','mg','1','IV'),
	(60,'Pemetrexed','21','Pemetrexed','500','mg/m2','1','IV'),
	(61,'Ramucirumab','14','Ramucirumab','8','mg/kg','1','IV'),
	(62,'Repotrectinib','-','Repotrectinib','-','-','-','IV'),
	(67,'Vemurafenib-Dabrafenib','-','Vemurafenib','960','mg/j','tous les jours','Orale'),
	(67,'Vemurafenib-Dabrafenib','-','Dabrafenib','150','mg x2/j','tous les jours','Orale');

INSERT INTO prescription (molecule, dose, unite, poids, taille, age, formule, sexe, clcr, creatinine, jour_prod)
VALUES 
('Carboplatine', 50, 'auc', 70.0, 180.0, 40.0, 'MDRD', 'homme', 80.0, 1.2, '2023-02-17'),
('nabPaclitaxel', 100, 'mg/m2', 70.0, 180.0, 40.0, 'MDRD', 'femme', 80.0, 1.2, '2023-02-17');


