INSERT INTO Chimiothrapie VALUES (1001,'Epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Paclitaxel hebdomadaire-Carboplatine',58),
	(1001,'Epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1001,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1001,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Pemetrexed',36),
	(1001,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Paclitaxel hebdomadaire-Carboplatine',58),
	(1001,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1003,'N/A','INF30','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Osimertinib',56),
	(1003,'Epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1003,'Epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1003,'Epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1003,'Epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1003,'Epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1003,'Epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1003,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Gemcitabine',34),
	(1003,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Docetaxel',33),
	(1003,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 50-Vinorelbine 25',29),
	(1003,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 100-Vinorelbine 30',26),
	(1003,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 75-Vinorelbine 25',32),
	(1003,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1003,'Non epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1003,'Non epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1003,'Non epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1003,'Non epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1003,'Non epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1003,'Non epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1003,'Non epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1003,'Non epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1003,'Non epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1003,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Pemetrexed',36),
	(1003,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 50-Vinorelbine 25',29),
	(1003,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 100-Vinorelbine 30',26),
	(1003,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 75-Vinorelbine 25',32),
	(1003,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1003,'Epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Paclitaxel hebdomadaire-Carboplatine',58),
	(1003,'Epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1003,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1003,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Pemetrexed',36),
	(1003,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Paclitaxel hebdomadaire-Carboplatine',58),
	(1003,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1003,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 50-Vinorelbine 25',19),
	(1004,'N/A','INF30','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Osimertinib',56),
	(1004,'Epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1004,'Epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1004,'Epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1004,'Epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1004,'Epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1004,'Epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1004,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Gemcitabine',34),
	(1004,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Docetaxel',33),
	(1004,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 50-Vinorelbine 25',29),
	(1004,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 100-Vinorelbine 30',26),
	(1004,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 75-Vinorelbine 25',32),
	(1004,'Epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1004,'Non epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1004,'Non epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1004,'Non epidermoide','INF60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1004,'Non epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1004,'Non epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1004,'Non epidermoide','INF60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1004,'Non epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Paclitaxel',19),
	(1004,'Non epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Gemcitabine',15),
	(1004,'Non epidermoide','SUP60','atteinte auditive','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1004,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Pemetrexed',36),
	(1004,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 50-Vinorelbine 25',29),
	(1004,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 100-Vinorelbine 30',26),
	(1004,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 75-Vinorelbine 25',32),
	(1004,'Non epidermoide','SUP60','Fonction auditive normale','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1005,'Epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Paclitaxel hebdomadaire-Carboplatine',58),
	(1005,'Epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1005,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Pemetrexed',22),
	(1005,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Pemetrexed',36),
	(1005,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Paclitaxel hebdomadaire-Carboplatine',58),
	(1005,'Non epidermoide','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine-Etoposide',27),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Pembrolizumab',59),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Pembrolizumab',59),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Pembrolizumab',59),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab 840',3),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab 1200',4),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab 1680',5),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab 840',3),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab 1200',4),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab 1680',5),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab 840',3),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab 1200',4),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab 1680',5),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Cemiplimab-rwlc',24),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Cemiplimab-rwlc',24),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Cemiplimab-rwlc',24),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Pembrolizumab',59),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Pembrolizumab',59),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Pembrolizumab',59),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Docetaxel',13),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Etoposide',14),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','nabPaclitaxel',51),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Docetaxel',41),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Gemcitabine',46),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Epidermoide','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Paclitaxel',57),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Dabrafenib-Trametinib',39),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Dabrafenib-Trametinib',39),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Dabrafenib-Trametinib',39),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Dabrafenib-Trametinib',39),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Docetaxel',13),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Docetaxel',13),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Docetaxel',33),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Docetaxel',33),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Etoposide',27),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Etoposide',27),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Gemcitabine',34),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Gemcitabine',34),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Paclitaxel',35),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Paclitaxel',35),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Dabrafenib-Trametinib',39),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Docetaxel',13),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Etoposide',14),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','nabPaclitaxel',51),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Docetaxel',41),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Gemcitabine',46),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Epidermoide','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Paclitaxel',57),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Pembrolizumab',59),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Pembrolizumab',59),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Pembrolizumab',59),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab 840',3),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab 1200',4),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab 1680',5),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab 840',3),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab 1200',4),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab 1680',5),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab 840',3),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab 1200',4),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab 1680',5),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Cemiplimab-rwlc',24),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Cemiplimab-rwlc',24),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Cemiplimab-rwlc',24),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','2','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','0','N/A','Pembrolizumab',59),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','1','N/A','Pembrolizumab',59),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif <= 50%','2','N/A','Pembrolizumab',59),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7);

INSERT INTO Chimiothrapie VALUES (1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Nivolumab-Ipilimumab-Carboplatine-Pemetrexed',53),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','0','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','1','N/A','Nivolumab-Ipilimumab-Cisplatine-Pemetrexed',54),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Pemetrexed',22),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Docetaxel',13),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Etoposide',14),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','nabPaclitaxel',51),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Docetaxel',41),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Gemcitabine',46),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Paclitaxel',57),
	(1006,'Adenocarcinome','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Negatif','2','N/A','Pemetrexed',60),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Dabrafenib-Trametinib',39),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Dabrafenib-Trametinib',39),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Carboplatine-Pemetrexed-Pembrolizumab',23),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Cisplatine-Pemetrexed -Pembrolizumab',37),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Atezolizumab-Bevacizumab-Carboplatine-Paclitaxel',6),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Atezolizumab-Carboplatine-nabPaclitaxel',7),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Nivolumab-Ipilimumab',52),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','0','N/A','Nivolumab-Ipilimumab-Pemetrexed',55),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Positif','1','N/A','Nivolumab-Ipilimumab-Pemetrexed',55),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Dabrafenib-Trametinib',39),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Dabrafenib-Trametinib',39),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Bevacizumab-Carboplatine-Paclitaxel',9),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Bevacizumab-Carboplatine-Paclitaxel',9),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Bevacizumab-Cisplatine-Pemetrexed',11),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Bevacizumab-Cisplatine-Pemetrexed',11),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Bevacizumab-Carboplatine-Pemetrexed',10),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Bevacizumab-Carboplatine-Pemetrexed',10),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Docetaxel',13),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Docetaxel',13),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Etoposide',14),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Etoposide',14),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Carboplatine-Pemetrexed',22),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Carboplatine-Pemetrexed',22),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Docetaxel',33),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Docetaxel',33),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Etoposide',27),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Etoposide',27),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Gemcitabine',34),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Gemcitabine',34),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Paclitaxel',35),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Paclitaxel',35),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Pemetrexed',36),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Pemetrexed',36),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Dabrafenib-Trametinib',39),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Vemurafenib-Dabrafenib',67),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Pemetrexed',22),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-nabPaclitaxel',16),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Docetaxel',13),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Etoposide',14),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Gemcitabine',15),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Carboplatine-Paclitaxel',19),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','nabPaclitaxel',51),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Docetaxel',41),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Gemcitabine',46),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Gemcitabine-Docetaxel',47),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Gemcitabine-Vinorelbine',48),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Paclitaxel',57),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','N/A','2','N/A','Pemetrexed',60),
	(1006,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','3','N/A','Meilleurs soins de soutien',50),
	(1006,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','4','N/A','Meilleurs soins de soutien',50),
	(1006,'N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','Alectinib',2),
	(1006,'N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','Brigatinib',12),
	(1006,'N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','Lorlatinib',49),
	(1006,'N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','Ceritinib',25),
	(1006,'N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','Crizotinib',38),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Osimertinib',56),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Gefitinib',44),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Erlotinib',43),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','bevacizumab',8),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','ramucirumab',61),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Afatinib',1),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Dacomitinib',40),
	(1006,'N/A','N/A','N/A','Positif','N/A','N/A','N/A','N/A','N/A','N/A','Gefitinib-Carboplatine-Pemetrexed',45),
	(1006,'N/A','N/A','N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','Entrectinib',42),
	(1006,'N/A','N/A','N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','Crizotinib',38),
	(1006,'N/A','N/A','N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','Ceritinib',25),
	(1006,'N/A','N/A','N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','Lorlatinib',49),
	(1006,'N/A','N/A','N/A','N/A','N/A','N/A','Positif','N/A','N/A','N/A','Repotrectinib',62),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','0','N/A','Cisplatine-Pemetrexed',35),
	(1006,'Adenocarcinome','N/A','N/A','N/A','N/A','Positif','N/A','Negatif','1','N/A','Cisplatine-Pemetrexed',35),
	(1007,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 75 + Etoposide',31),
	(1007,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 60 + Etoposide',30),
	(1007,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Cisplatine 25 + Etoposide',28),
	(1007,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Carboplatine-Etoposide',14),
	(1007,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Negatif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Negatif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Positif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Positif','N/A','N/A','Non fumeur','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Positif','Positif','Negatif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Positif','Positif','Negatif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Positif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Positif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Negatif','Positif','N/A','N/A','Non fumeur','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Negatif','Positif','N/A','N/A','Non fumeur','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Positif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Positif','Negatif','N/A','N/A','Non fumeur','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Negatif','Positif','N/A','N/A','Non fumeur','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Negatif','Positif','N/A','N/A','Non fumeur','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Positif','Positif','N/A','N/A','Non fumeur','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Positif','Positif','N/A','N/A','Non fumeur','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','Non fumeur','Pembrolizumab',59),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','Non fumeur','Atezolizumab 840',3),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','Non fumeur','Atezolizumab 1200',4),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','Non fumeur','Atezolizumab 1680',5),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','Non fumeur','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','Non fumeur','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','Non fumeur','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','Non fumeur','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','Non fumeur','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','Non fumeur','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','Non fumeur','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','Non fumeur','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','Non fumeur','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','Non fumeur','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','Non fumeur','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','Non fumeur','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','Non fumeur','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','Non fumeur','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','Non fumeur','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','3','Non fumeur','Meilleurs soins de soutien',50),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','4','Non fumeur','Meilleurs soins de soutien',50),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Negatif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Negatif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Positif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Positif','N/A','N/A','INF15PA','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Positif','Positif','Negatif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Positif','Positif','Negatif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Positif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Positif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Negatif','Positif','N/A','N/A','INF15PA','Therapie ciblee anti-EGFR',65),
	(1008,'N/A','N/A','N/A','Positif','Negatif','Negatif','Positif','N/A','N/A','INF15PA','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Positif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Positif','Negatif','N/A','N/A','INF15PA','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Negatif','Positif','N/A','N/A','INF15PA','Therapie ciblee anti-ALK',63),
	(1008,'N/A','N/A','N/A','Negatif','Positif','Negatif','Positif','N/A','N/A','INF15PA','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Positif','Positif','N/A','N/A','INF15PA','Therapie ciblee anti-RoS1',66),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Positif','Positif','N/A','N/A','INF15PA','Therapie ciblee anti-BRAF',64),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','INF15PA','Pembrolizumab',59),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','INF15PA','Atezolizumab 840',3),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','INF15PA','Atezolizumab 1200',4),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','Positif > 50%','N/A','INF15PA','Atezolizumab 1680',5),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','INF15PA','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','INF15PA','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','INF15PA','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','INF15PA','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','INF15PA','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','INF15PA','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','INF15PA','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','INF15PA','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','INF15PA','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','INF15PA','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','INF15PA','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','INF15PA','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','0','INF15PA','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','1','INF15PA','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','2','INF15PA','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','3','INF15PA','Meilleurs soins de soutien',50),
	(1008,'N/A','N/A','N/A','Negatif','Negatif','Negatif','Negatif','N/A','4','INF15PA','Meilleurs soins de soutien',50),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','Positif > 50%','N/A','SUP15PA','Pembrolizumab',59),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','Positif > 50%','N/A','SUP15PA','Atezolizumab 840',3),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','Positif > 50%','N/A','SUP15PA','Atezolizumab 1200',4),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','Positif > 50%','N/A','SUP15PA','Atezolizumab 1680',5),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','0','SUP15PA','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','1','SUP15PA','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','2','SUP15PA','Nivolumab-Ipilimumab',52),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','0','SUP15PA','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','1','SUP15PA','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','2','SUP15PA','Carboplatine-Paclitaxel-Pembrolizumab',21),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','0','SUP15PA','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','1','SUP15PA','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','2','SUP15PA','Carboplatine-nabPaclitaxel-Pembrolizumab',18),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','0','SUP15PA','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','1','SUP15PA','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','2','SUP15PA','Carboplatine-Paclitaxel-Nivolumab-Ipilimumab',20),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','0','SUP15PA','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','1','SUP15PA','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','2','SUP15PA','Carboplatine-nab-Paclitaxel-Nivolumab-Ipilimumab',17),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','3','SUP15PA','Meilleurs soins de soutien',50),
	(1008,'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','4','SUP15PA','Meilleurs soins de soutien',50);
