version: '3.9'

    
services:

  # front container
  front-app:
    container_name: mcda-front
    image: front-mcda:latest
    build: ../front/    
    env_file:
      - .env
    ports:
      - $FRONT_LOCAL_PORT:$FRONT_DOCKER_PORT
   
  # database
  mysqldb:
    container_name: db-mcda
    image: mysql:latest
    env_file:
      - .env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    volumes:
      - db:/var/lib/mysql
    
   # api container
  springboot-app:
    restart: always
    container_name: mcda-api
    image: mcda-api:latest
    build: ../api/
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2 
    depends_on:
      - mysqldb
  
volumes:
  db:
  
  
  

  

  
  
        
